### ISSUE TITLE
Ping event

### ISSUE THREAD

**Issue by gaborszita** [MiloBotDev/MiloBot#77]
When the user pings the bot, the bot should reply with its prefix.

**Comment by RubenJ01** [comment]
This has now been implemented, but I noticed that this also happens when you reply to the message of a bot. Maybe we could look into a fix for this.

**Comment by gaborszita** [comment]
> This has now been implemented, but I noticed that this also happens when you reply to the message of a bot. Maybe we could look into a fix for this.

Addressed by #95
